spring.application.name=dbBoot


## default connection pool
spring.datasource.hikari.connectionTimeout=20000
spring.datasource.hikari.maximumPoolSize=5

## Neon PostgreSQL (cloud)
spring.datasource.url=jdbc:postgresql://ep-cold-leaf-atz43icc.c-9.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_PgJw8yN1kmBd
## PostgreSQL

# create and drop table, good for testing, production set to none or comment it
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
